
lazy val config = project.in(file("config"))
  .settings(name := "plotka-config")
  .settings(Common.settings)
  .settings(Common.testCoverageSettings)
  .settings(Common.publishingSettings)
  .settings(Common.dependencies)
  .settings(libraryDependencies ++= Common.Dependencies.consul)

lazy val networking = project.in(file("networking"))
  .settings(name := "plotka-networking")
  .settings(Common.settings)
  .settings(Common.testCoverageSettings)
  .settings(Common.publishingSettings)
  .settings(Common.dependencies)
  .settings(libraryDependencies ++= Common.Dependencies.serialization)
  .dependsOn(config)

lazy val framework = project.in(file("framework"))
  .settings(name := "plotka-framework")
  .settings(Common.settings)
  .settings(Common.testCoverageSettings)
  .settings(Common.publishingSettings)
  .settings(libraryDependencies ++= Common.Dependencies.consul)
  .settings(libraryDependencies ++= Common.Dependencies.testing)
  .dependsOn(networking)

lazy val plotka = project.in(file("."))
  .enablePlugins(ScalaUnidocPlugin)
  .settings(name := "plotka")
  .settings(Common.settings)
  .settings(Common.publishingSettings)
  .aggregate(config, networking, framework)
  .dependsOn(config, networking, framework)


addCommandAlias("release", ";clean;coverage;test;coverageReport;clean;coverageOff;publish")
